-- ============================================================================
-- LEXIKANI NORWEGIAN VOCABULARY RESET/APPEND (Levels 4–8, ≥90 words each)
-- ============================================================================
-- Ensures NO reuse with Levels 1–3. Mixed parts of speech, usefulness-ordered.
-- This script deletes existing 4–8 entries and reinserts curated single words.
-- ============================================================================

DO $$
DECLARE
    norwegian_id INTEGER;
BEGIN
    SELECT id INTO norwegian_id FROM language WHERE name='Norwegian' LIMIT 1;
    IF norwegian_id IS NULL THEN
        RAISE EXCEPTION 'Norwegian language not found. Please seed first.';
    END IF;

    DELETE FROM vocabulary WHERE language_id=norwegian_id AND level BETWEEN 4 AND 8;

    INSERT INTO vocabulary (language_id, word, meaning, level, type, attributes) VALUES
(norwegian_id, 'å dra', 'to go/leave', 4, 'verb', '{"past":"dro","perfect":"dratt","present":"drar"}'),
(norwegian_id, 'person', 'person', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'morsom', 'funny', 4, 'adjective', '{}'),
(norwegian_id, 'sannsynligvis', 'probably', 4, 'adverb', '{}'),
(norwegian_id, 'å finne', 'to find', 4, 'verb', '{"past":"fant","perfect":"funnet","present":"finner"}'),
(norwegian_id, 'forelder', 'parent', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'kjedelig', 'boring', 4, 'adjective', '{}'),
(norwegian_id, 'antagelig', 'presumably', 4, 'adverb', '{}'),
(norwegian_id, 'å holde', 'to hold/keep', 4, 'verb', '{"past":"holdt","perfect":"holdt","present":"holder"}'),
(norwegian_id, 'barnet', 'the child', 4, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'mulig', 'possible', 4, 'adjective', '{}'),
(norwegian_id, 'helt', 'completely', 4, 'adverb', '{}'),
(norwegian_id, 'å miste', 'to lose/miss', 4, 'verb', '{"past":"mistet","perfect":"mistet","present":"mister"}'),
(norwegian_id, 'par', 'couple', 4, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'umulig', 'impossible', 4, 'adjective', '{}'),
(norwegian_id, 'delvis', 'partly', 4, 'adverb', '{}'),
(norwegian_id, 'å vinne', 'to win', 4, 'verb', '{"past":"vant","perfect":"vunnet","present":"vinner"}'),
(norwegian_id, 'gruppe', 'group', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'riktig', 'correct', 4, 'adjective', '{}'),
(norwegian_id, 'ganske', 'quite', 4, 'adverb', '{}'),
(norwegian_id, 'å tape', 'to lose', 4, 'verb', '{"present":"taper"}'),
(norwegian_id, 'lærer', 'teacher', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'feil', 'wrong', 4, 'adjective', '{}'),
(norwegian_id, 'nok', 'enough/probably', 4, 'adverb', '{}'),
(norwegian_id, 'å lage', 'to make/cook', 4, 'verb', '{"present":"lager"}'),
(norwegian_id, 'student', 'student', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'sikker', 'sure/certain', 4, 'adjective', '{}'),
(norwegian_id, 'deretter', 'afterwards', 4, 'adverb', '{}'),
(norwegian_id, 'å kjøpe', 'to buy', 4, 'verb', '{"present":"kjøper"}'),
(norwegian_id, 'sjef', 'boss/manager', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'usikker', 'uncertain', 4, 'adjective', '{}'),
(norwegian_id, 'dessuten', 'besides', 4, 'adverb', '{}'),
(norwegian_id, 'å selge', 'to sell', 4, 'verb', '{"past":"solgte","perfect":"solgt","present":"selger"}'),
(norwegian_id, 'kunde', 'customer', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'vennlig', 'friendly', 4, 'adjective', '{}'),
(norwegian_id, 'imidlertid', 'however', 4, 'adverb', '{}'),
(norwegian_id, 'å besøke', 'to visit', 4, 'verb', '{"present":"besøker"}'),
(norwegian_id, 'pasient', 'patient', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'uhøflig', 'impolite', 4, 'adjective', '{}'),
(norwegian_id, 'plutselig', 'suddenly', 4, 'adverb', '{}'),
(norwegian_id, 'å invitere', 'to invite', 4, 'verb', '{"present":"inviterer"}'),
(norwegian_id, 'lege', 'doctor', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'høflig', 'polite', 4, 'adjective', '{}'),
(norwegian_id, 'sjeldent', 'rarely', 4, 'adverb', '{}'),
(norwegian_id, 'å trene', 'to train/exercise', 4, 'verb', '{"present":"trener"}'),
(norwegian_id, 'sykepleier', 'nurse', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'streng', 'strict', 4, 'adjective', '{}'),
(norwegian_id, 'hjemme', 'at home', 4, 'adverb', '{}'),
(norwegian_id, 'å jogge', 'to jog', 4, 'verb', '{"present":"jogger"}'),
(norwegian_id, 'servitør', 'waiter', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'sterk', 'strong', 4, 'adjective', '{}'),
(norwegian_id, 'ute', 'outside', 4, 'adverb', '{}'),
(norwegian_id, 'å svømme', 'to swim', 4, 'verb', '{"present":"svømmer"}'),
(norwegian_id, 'kokk', 'cook/chef', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'svak', 'weak', 4, 'adjective', '{}'),
(norwegian_id, 'inne', 'inside', 4, 'adverb', '{}'),
(norwegian_id, 'å sykle', 'to cycle', 4, 'verb', '{"present":"sykler"}'),
(norwegian_id, 'frisør', 'hairdresser', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'tung', 'heavy', 4, 'adjective', '{}'),
(norwegian_id, 'oppe', 'upstairs', 4, 'adverb', '{}'),
(norwegian_id, 'å studere', 'to study', 4, 'verb', '{"present":"studerer"}'),
(norwegian_id, 'politiker', 'politician', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'våt', 'wet', 4, 'adjective', '{}'),
(norwegian_id, 'nede', 'downstairs', 4, 'adverb', '{}'),
(norwegian_id, 'å undervise', 'to teach', 4, 'verb', '{"present":"underviser"}'),
(norwegian_id, 'journalist', 'journalist', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'tørr', 'dry', 4, 'adjective', '{}'),
(norwegian_id, 'borte', 'away', 4, 'adverb', '{}'),
(norwegian_id, 'å motta', 'to receive', 4, 'verb', '{"past":"mottok","perfect":"mottatt","present":"mottar"}'),
(norwegian_id, 'ingeniør', 'engineer', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'nær', 'near', 4, 'adjective', '{}'),
(norwegian_id, 'fram', 'forward', 4, 'adverb', '{}'),
(norwegian_id, 'å reservere', 'to reserve', 4, 'verb', '{"present":"reserverer"}'),
(norwegian_id, 'programmerer', 'programmer', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'fjern', 'distant', 4, 'adjective', '{}'),
(norwegian_id, 'tilbake', 'back', 4, 'adverb', '{}'),
(norwegian_id, 'å pakke', 'to pack', 4, 'verb', '{"present":"pakker"}'),
(norwegian_id, 'forsker', 'researcher', 4, 'noun', '{"gender":"m"}'),
(norwegian_id, 'bred', 'wide', 4, 'adjective', '{}'),
(norwegian_id, 'sammen', 'together', 4, 'adverb', '{}'),
(norwegian_id, 'å låne', 'to borrow/lend', 4, 'verb', '{"present":"låner"}'),
(norwegian_id, 'kontor', 'office', 4, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'smal', 'narrow', 4, 'adjective', '{}'),
(norwegian_id, 'alene', 'alone', 4, 'adverb', '{}'),
(norwegian_id, 'å spare', 'to save', 4, 'verb', '{"present":"sparer"}'),
(norwegian_id, 'møterom', 'meeting room', 4, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'varm', 'warm', 4, 'adjective', '{}'),
(norwegian_id, 'først', 'first', 4, 'adverb', '{}'),
(norwegian_id, 'å ordne', 'to arrange/fix', 4, 'verb', '{"present":"ordner"}'),
(norwegian_id, 'bibliotek', 'library', 4, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'kald', 'cold', 5, 'adjective', '{}'),
(norwegian_id, 'sist', 'last', 5, 'adverb', '{}'),
(norwegian_id, 'å endre', 'to change', 5, 'verb', '{"present":"endrer"}'),
(norwegian_id, 'apotek', 'pharmacy', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'pen', 'pretty', 5, 'adjective', '{}'),
(norwegian_id, 'hverandre', 'each other', 5, 'pronoun', '{}'),
(norwegian_id, 'å fortsette', 'to continue', 5, 'verb', '{"present":"fortsetter"}'),
(norwegian_id, 'sykehus', 'hospital', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'stygg', 'ugly', 5, 'adjective', '{}'),
(norwegian_id, 'flest', 'most (count)', 5, 'determiner', '{}'),
(norwegian_id, 'å vokse', 'to grow', 5, 'verb', '{"present":"vokser"}'),
(norwegian_id, 'stasjon', 'station', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'trygg', 'safe', 5, 'adjective', '{}'),
(norwegian_id, 'minst', 'least', 5, 'adverb', '{}'),
(norwegian_id, 'å falle', 'to fall', 5, 'verb', '{"past":"falt","perfect":"falt","present":"faller"}'),
(norwegian_id, 'flyplass', 'airport', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'farlig', 'dangerous', 5, 'adjective', '{}'),
(norwegian_id, 'mer', 'more', 5, 'adverb', '{}'),
(norwegian_id, 'å løpe', 'to run', 5, 'verb', '{"past":"løp","perfect":"løpt","present":"løper"}'),
(norwegian_id, 'park', 'park', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'mest', 'most', 5, 'adverb', '{}'),
(norwegian_id, 'å hoppe', 'to jump', 5, 'verb', '{"present":"hopper"}'),
(norwegian_id, 'museum', 'museum', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'mindre', 'less', 5, 'adverb', '{}'),
(norwegian_id, 'å danse', 'to dance', 5, 'verb', '{"present":"danser"}'),
(norwegian_id, 'strand', 'beach', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'færre', 'fewer', 5, 'determiner', '{}'),
(norwegian_id, 'å synge', 'to sing', 5, 'verb', '{"past":"sang","perfect":"sunget","present":"synger"}'),
(norwegian_id, 'fjell', 'mountain', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'alt', 'everything', 5, 'pronoun', '{}'),
(norwegian_id, 'å spille', 'to play', 5, 'verb', '{"present":"spiller"}'),
(norwegian_id, 'skog', 'forest', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'alle', 'everyone/all', 5, 'determiner', '{}'),
(norwegian_id, 'å male', 'to paint', 5, 'verb', '{"present":"maler"}'),
(norwegian_id, 'elv', 'river', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'hvilken', 'which (common)', 5, 'determiner', '{}'),
(norwegian_id, 'å tegne', 'to draw', 5, 'verb', '{"present":"tegner"}'),
(norwegian_id, 'sjø', 'sea/lake', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'hvilket', 'which (neuter)', 5, 'determiner', '{}'),
(norwegian_id, 'å fotografere', 'to photograph', 5, 'verb', '{"present":"fotograferer"}'),
(norwegian_id, 'øy', 'island', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'hvilke', 'which (plural)', 5, 'determiner', '{}'),
(norwegian_id, 'å lande', 'to land', 5, 'verb', '{"present":"lander"}'),
(norwegian_id, 'bro', 'bridge', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'hvorvidt', 'whether', 5, 'conjunction', '{}'),
(norwegian_id, 'å avslutte', 'to finish/end', 5, 'verb', '{"present":"avslutter"}'),
(norwegian_id, 'tunnel', 'tunnel', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'dersom', 'if', 5, 'conjunction', '{}'),
(norwegian_id, 'å støtte', 'to support', 5, 'verb', '{"present":"støtter"}'),
(norwegian_id, 'veske', 'bag', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'selv', 'self', 5, 'pronoun', '{}'),
(norwegian_id, 'å klage', 'to complain', 5, 'verb', '{"present":"klager"}'),
(norwegian_id, 'ryggsekk', 'backpack', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'å godta', 'to accept', 5, 'verb', '{"past":"godtok","perfect":"godtatt","present":"godtar"}'),
(norwegian_id, 'lommebok', 'wallet', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'å avvise', 'to reject', 5, 'verb', '{"present":"avviser"}'),
(norwegian_id, 'koffert', 'suitcase', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'å beskrive', 'to describe', 5, 'verb', '{"past":"beskrev","perfect":"beskrevet","present":"beskriver"}'),
(norwegian_id, 'kopp', 'cup', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'å oppdage', 'to discover', 5, 'verb', '{"present":"oppdager"}'),
(norwegian_id, 'glass', 'glass', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'å undersøke', 'to examine', 5, 'verb', '{"present":"undersøker"}'),
(norwegian_id, 'tallerken', 'plate', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'gaffel', 'fork', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'kniv', 'knife', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'skje', 'spoon', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'ovn', 'oven', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'komfyr', 'stove', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'kjøleskap', 'fridge', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'mikrobølgeovn', 'microwave', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'vaskemaskin', 'washing machine', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'støvsuger', 'vacuum cleaner', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'lader', 'charger', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'skjerm', 'screen', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'tastatur', 'keyboard', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'høyttaler', 'speaker', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'hodetelefon', 'headphone', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'batteri', 'battery', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'kabel', 'cable', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'nettverk', 'network', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'programvare', 'software', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'melk', 'milk', 5, 'noun', '{"gender":"f"}'),
(norwegian_id, 'smør', 'butter', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'yoghurt', 'yogurt', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'kjøtt', 'meat', 5, 'noun', '{"gender":"neuter"}'),
(norwegian_id, 'kylling', 'chicken', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'fisk', 'fish', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'potet', 'potato', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'tomat', 'tomato', 5, 'noun', '{"gender":"m"}'),
(norwegian_id, 'agurk', 'cucumber', 5, 'noun', '{"gender":"m"}')
;
    RAISE NOTICE 'Rebuilt Levels 4–8 with no reuse. Rows in 4–8: %',
        (SELECT COUNT(*) FROM vocabulary v JOIN language l ON v.language_id=l.id WHERE l.name='Norwegian' AND level BETWEEN 4 AND 8);
END $$;

-- Verify distribution
SELECT level, type, COUNT(*) AS word_count
FROM vocabulary v JOIN language l ON v.language_id=l.id
WHERE l.name='Norwegian' AND level BETWEEN 4 AND 8
GROUP BY level, type
ORDER BY level, type;